/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Bibor
 */
public class dolgozok extends javax.swing.JPanel {

    /**
     * Creates new form dolgozok
     */
    public dolgozok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        fiukJCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        lanyokJCB = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        lanyJRB = new javax.swing.JRadioButton();
        fiuJRB = new javax.swing.JRadioButton();
        legidosebbJL = new javax.swing.JLabel();
        osszesKorJL = new javax.swing.JLabel();
        eveDolgozikJL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        korJL = new javax.swing.JLabel();
        miotaDolgozikJL = new javax.swing.JLabel();
        mindkettoNemJCB = new javax.swing.JCheckBox();
        mentJB = new javax.swing.JButton();

        jLabel1.setText("Lányok");

        jLabel2.setText("Fiúk");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("összesítő"));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        buttonGroup1.add(lanyJRB);
        lanyJRB.setText("lány");
        lanyJRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lanyJRBActionPerformed(evt);
            }
        });

        buttonGroup1.add(fiuJRB);
        fiuJRB.setText("fiú");

        legidosebbJL.setText("legidősebb:");

        osszesKorJL.setText("összes kor:");

        eveDolgozikJL.setText("6 éve dolgozó:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lanyJRB)
                        .addGap(37, 37, 37)
                        .addComponent(fiuJRB))
                    .addComponent(legidosebbJL)
                    .addComponent(osszesKorJL)
                    .addComponent(eveDolgozikJL))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lanyJRB)
                    .addComponent(fiuJRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(legidosebbJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(osszesKorJL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eveDolgozikJL)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("adatok"));

        korJL.setText("kor:");

        miotaDolgozikJL.setText("mióta dolgozik:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(korJL)
                    .addComponent(miotaDolgozikJL))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(korJL)
                .addGap(18, 18, 18)
                .addComponent(miotaDolgozikJL)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        mindkettoNemJCB.setText("Mindkettő nem");
        mindkettoNemJCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mindkettoNemJCBActionPerformed(evt);
            }
        });

        mentJB.setText("Ment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lanyokJCB, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fiukJCB, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(mindkettoNemJCB)
                            .addComponent(mentJB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lanyokJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiukJCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mindkettoNemJCB)
                        .addGap(18, 18, 18)
                        .addComponent(mentJB))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleName("összesítő");
        jPanel2.getAccessibleContext().setAccessibleName("Adatok");
    }// </editor-fold>//GEN-END:initComponents

    private void lanyJRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lanyJRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lanyJRBActionPerformed

    private void mindkettoNemJCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mindkettoNemJCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mindkettoNemJCBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel eveDolgozikJL;
    private javax.swing.JRadioButton fiuJRB;
    private javax.swing.JComboBox<String> fiukJCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel korJL;
    private javax.swing.JRadioButton lanyJRB;
    private javax.swing.JComboBox<String> lanyokJCB;
    private javax.swing.JLabel legidosebbJL;
    private javax.swing.JButton mentJB;
    private javax.swing.JCheckBox mindkettoNemJCB;
    private javax.swing.JLabel miotaDolgozikJL;
    private javax.swing.JLabel osszesKorJL;
    // End of variables declaration//GEN-END:variables
}
